[package]
name = "p0nygramm"
version = "0.1.0"
authors = ["Voldracarno Draconor <ThaFireDragonOfDeath@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2.1"
actix-multipart = "0.2.0"
actix-rt = "1.0.0"
actix-session = "0.3.0"
#actix-web = { version = "2.0.0", features=["rustls"]}
actix-web = "2.0.0"
argonautica = { version = "0.2.0", features = ["simd"] }
#chrono = "0.4.10"
futures-core = "0.3.4"
#handlebars = "3.0.1"
redis = "0.15.1"
serde_json = "1.0.46"
tokio = { version = "0.2.12", features = ["rt-core"] }
tokio-postgres = "0.5.2"
toml = "0.5.6"
v_htmlescape = "0.4.5"
