# Contains the default config (includes in binary)
# Configs can be overlayed with the user config file

# Set the application configs
[application]
max_upload_size = "20" # Maximum filesize of uploads in MB

# Set the paths of the static webcontent, template and upload files
[filesystem]
ffprobe_path = "/usr/bin/ffprobe" # Path to ffprobe binary (part of ffmpeg)
static_webcontent_path = "/srv/p0nygramm/static/webcontent"
uploads_path = "/srv/p0nygramm/static/uploads"

# Set on which ip and port %project_name% will listen
[network]
ip_addr = "127.0.0.1"
port = "8080"

# Set the postgessql db connection parameters
[postgres]
host = "127.0.0.1"
port = "5432"
unix_socket_dir = "/run/postgres" # The socket file is unix_socket_dir/db_name
connection_method = "tcp" # Can be either 'tcp' or 'unix_socket'
user = "postgres"
password = ""
db_name = "p0nygramm"

# Set the redis db connection parameters
[redis]
host = "127.0.0.1"
port = "6379"
unix_socket_file = "/tmp/redis.sock"
connection_method = "tcp" # Can be either 'tcp' or 'unix_socket'

# Set security relevant options
[security]
session_private_key = "" # Private key to secure cookie sessions (have to be a minimum length of 32 bytes)
password_hash_key = "" # Private key to secure hash passwords (argon2 secret key feature) (minimal length: 8 bytes)
